// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://licnranlywyyulfuasuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpY25yYW5seXd5eXVsZnVhc3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDEwNDAsImV4cCI6MjA2OTIxNzA0MH0.3sjXl91Zspvm-y98Y3HvUQ2A9Yp3g1vtXzonmZm9b10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});